[package]
name = "catmark"
version = "0.1.0"
authors = [ "Xavier Bestel <xavier.bestel@free.fr>" ]
license = "GPL"
description = "Console printer for CommonMark"
repository = "https://github.com/bestouff/catmark"

[dependencies]
pulldown-cmark = "*"
ansi_term = "*"
syntect = "*"
unicode-segmentation = "*"
unicode-width = "*"
